vim.keymap.set("n", "<leader>gs", vim.cmd.Git)
vim.keymap.set("n", "<leader>ga", "<cmd>Git add .<CR>")
vim.keymap.set("n", "<leader>gp", "<cmd>Git push<CR>")
vim.keymap.set("n", "<leader>gpl", "<cmd>Git pull<CR>")
vim.keymap.set("n", "<leader>gl", "<cmd>Git log <CR>")
vim.keymap.set("n", "<leader>gh", "<cmd>Git hist <CR>")
vim.keymap.set("n", "<leader>gr", "<cmd>Git rank<CR>")
vim.keymap.set("n", "<leader>grh", "<cmd>Git rehard<CR>")
